// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgkshOP4hM3N-z8TUV-1-uBggfT6D8ZYs',
    appId: '1:960742786089:web:d95aaac6f03c67dadd0838',
    messagingSenderId: '960742786089',
    projectId: 'herb-ar',
    authDomain: 'herb-ar.firebaseapp.com',
    storageBucket: 'herb-ar.appspot.com',
    measurementId: 'G-FLFTNEDST5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXA-41G-o3_W-2I6yanPzhInEcbZLVBo4',
    appId: '1:960742786089:android:679e45bebb350221dd0838',
    messagingSenderId: '960742786089',
    projectId: 'herb-ar',
    storageBucket: 'herb-ar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjssTYjcCI9tw6RAJnHKSBsibfUbCYAQ4',
    appId: '1:960742786089:ios:8ac9814e031a2d48dd0838',
    messagingSenderId: '960742786089',
    projectId: 'herb-ar',
    storageBucket: 'herb-ar.appspot.com',
    iosClientId: '960742786089-ed6r5bqpkkem8h4nvbc54l5poe69o2a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.herbAr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjssTYjcCI9tw6RAJnHKSBsibfUbCYAQ4',
    appId: '1:960742786089:ios:8ac9814e031a2d48dd0838',
    messagingSenderId: '960742786089',
    projectId: 'herb-ar',
    storageBucket: 'herb-ar.appspot.com',
    iosClientId: '960742786089-ed6r5bqpkkem8h4nvbc54l5poe69o2a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.herbAr',
  );
}
